name: Tests

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max-old-space-size=4096
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cache Yarn Cache
        uses: actions/cache@v2
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
      - name: Install modules
        run: yarn --frozen-lockfile
      - name: Run format linting
        run: yarn format:check
      - name: Run spellcheck test
        run: yarn test:spellcheck
      - name: Build website
        run: yarn build
      - name: Generate pages fixture
        run: node scripts/build-pages-fixture.js
      - name: Run e2e tests
        run: yarn e2e:headless
