name: Tests

on: pull_request

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache Yarn Cache
        uses: actions/cache@v2
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
      - name: Install modules
        run: yarn --frozen-lockfile
      - name: Run format linting
        run: yarn format:check
      - name: Run tests
        run: yarn test
      - name: Run spellcheck test
        run: yarn ci:rename-for-spellcheck && yarn test:spellcheck
